name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      contents:"write"

    steps:
    - uses: actions/checkout@v3
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install trunk
    - name: Build
      run: trunk build --release --public-url ahc-analyzer
    - run: cp -r ./dist ./public/
    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
